Documentation
openactive/models-ruby pull request #13
Opened 2019-11-28 15:50 UTC by ylt

2019-11-29 10:21 UTC, henryaddison approved these changes
Looks good, no major problems (remove a TODO from README given you've now done it!).

2019-11-29 10:21 UTC, henryaddison commented on README.md
>  TODO: Write usage instructions here
You can probably remove this unless you're planning on writing anything more

2019-11-29 10:21 UTC, henryaddison commented on README.md
> +json_Ld = OpenActive::Rpde::RpdeBody.create_from_next_change_number("https://www.example.com/feed", 2, items).to_json
```suggestion
json_ld = OpenActive::Rpde::RpdeBody.create_from_next_change_number("https://www.example.com/feed", 2, items).to_json
```

2019-11-29 11:03 UTC, henryaddison requested changes
Missing documentation on how to deserialize a model instance from JSON

2019-11-29 11:07 UTC, ylt commented on README.md
> +json_Ld = OpenActive::Rpde::RpdeBody.create_from_next_change_number("https://www.example.com/feed", 2, items).to_json
Good spot

2019-12-03 11:35 UTC, henryaddison approved these changes

2019-12-03 11:36 UTC, merged